google-gemini/generative-ai-swift

Package.swift, Tests/GoogleGenerativeAITests/GoogleGenerativeAITests.swift
1. Since April, the apps and SDKs must be built in Xcode 14.1 + to submit to the AppStore. To support Xcode 14.1, I modified the swift version to **5.7.1** from 5.8.0
> Reference: [developer.apple.com/ios/submit](https://developer.apple.com/ios/submit/#:~:text=Build%20with,iOS%2016.1%20SDK.)
2. I fixed the build errors on the tests.
=> [FIX] Modify swift version to 5.7.1 and fix test build error

.github/labeler.yml, .github/workflows/labeler.yml, .github/workflows/remove-issue-labels.yml, .github/workflows/remove-pr-labels.yml
1. Add "awaiting-review" to all opened PRs
2. Remove "status:X" labels when an issue is closed
3. Remove "status:X" labels when a PR is closed
cc @google/gtech-llm-support
=> Automatically add and remove specific labels

.github/workflows/stale.yml
Adding github action workflow to mark stale issues and prs. This stale management workflow will add stale label and post reminder message after 14 days of inactivity and further close issue/pr after another 14 days of inactivity. We can also override stale action by adding override-stale label. Thanks! cc @google/gtech-llm-support
=> Adding github action workflow to mark stale issues and prs.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/labeler.yml, .github/workflows/stale.yml
Change label "stale" -> "status:stale"
Automatically add "component:swift sdk" to opened issues and PRs
Part of the effort to structure and clean up labels
cc @google/gtech-llm-support 
Choose one: Other
=> Clean up labels + automation

Sources/GoogleAI/CountTokensRequest.swift, Sources/GoogleAI/Errors.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerateContentResponse.swift, Sources/GoogleAI/GenerationConfig.swift, Sources/GoogleAI/Safety.swift
- Conform to `Encodable` for request-only types
- Conform to `Decodable` for response-only types
> In some cases, you may not need Codable's support for bidirectional encoding and decoding. For example, some apps only need to make calls to a remote network API and do not need to decode a response containing the same type. __Declare conformance to Encodable if you only need to support the encoding of data. Conversely, declare conformance to Decodable if you only need to read data of a given type.__
-- https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types#2904056
Context: It's easier to add `Codable` conformance to our public API contract later, if needed, than to remove it if not needed.
=> Remove `Codable` conformance for request or response-only types

Tests/GoogleAITests/GenerativeModelTests.swift
Refactored `testGenerateContent_failure_emptyContent` to use `catch let GenerateContentError.internalError(underlying: underlyingError)`, avoiding the nullable variables outside the `do`/`catch`.
=> Refactor `testGenerateContent_failure_emptyContent` with `catch let`

Sources/GoogleAI/GenerationConfig.swift, Sources/GoogleAI/Safety.swift
Fixed the following warnings:
- `Sources/GoogleAI/GenerationConfig.swift:60:26: warning: 'String' doesn't exist at '/GoogleGenerativeAI/GenerationConfig/stopSequences'`
- Shouldn't use double backticks because `String` isn't a type provided by our library
- `Sources/GoogleAI/Safety.swift:22:9: warning: 'SafetySetting.HarmCategory' doesn't exist at '/GoogleGenerativeAI/SafetyRating/category'`
- DocC references use `/` instead of `.` for nested types
=> Fix DocC warnings when running `swift package generate-documentation`

.spi.yml
Added a Swift Package Index Manifest `.spi.yml` file so that DocC documentation is generated for the SDK and hosted at https://swiftpackageindex.com/google/generative-ai-swift. Configured to generate docs for iOS, rather than the default of macOS.
More Info: [Host DocC documentation in the Swift Package Index](https://swiftpackageindex.com/swiftpackageindex/spimanifest/1.1.1/documentation/spimanifest/commonusecases#Host-DocC-documentation-in-the-Swift-Package-Index)
=> Add SPI Manifest for DocC documentation generation / hosting

.spi.yml
Sets the author to "Google" for the [generative-ai-swift package](https://swiftpackageindex.com/google/generative-ai-swift) on Swift Package Index.
=> Set "Google" as the author on Swift Package Index

Examples/GenerativeAISample/ChatSample/Views/ErrorDetailsView.swift, Sources/GoogleAI/Safety.swift
This allows collections of `SafetyRating`s to be displayed in SwiftUI views, such as [`List`](https://developer.apple.com/documentation/swiftui/list), which require the elements to conform to [`Hashable`](https://developer.apple.com/documentation/swift/hashable).
Note: When moved into the SDK, the auto-synthesized `Hashable` conformance can be used ([SE-0185](https://github.com/apple/swift-evolution/blob/main/proposals/0185-synthesize-equatable-hashable.md)). This wasn't possible when conformance was implemented in the sample app (`Extension outside of file declaring struct 'SafetyRating' prevents automatic synthesis of 'hash(into:)' for protocol 'Hashable'`).
=> Make `SafetyRating` conform to `Hashable`

Sources/GoogleAI/Errors.swift, Tests/GoogleAITests/GenerativeModelTests.swift
- Added assertions verifying returned `RPCError`s in unary calls
- Changed from `Int32` to `Int` in `RPCError`
=> Add assertions in unary RPC error tests

Examples/GenerativeAISample/ChatSample/Views/MessageView.swift
Show system chat bubbles in gray to distinguish from user chat bubbles in blue
Differentiates system and user chat bubbles
Bug fix
=> Fix background color of system chat bubble

Sources/GoogleAI/CountTokensRequest.swift
Added documentation for the `countTokens` return type (`CountTokensResponse`).
=> Add documentation for `CountTokensResponse`

Examples/GenerativeAISample/ChatSample/Views/MessageView.swift
Use system colors to ensure chat bubbles have enough contrast both in light and dark mode.
This fixes #51 .
Choose one: Bug fix
=> Fix colors of chat bubbles so they work in light and dark mode

.spi.yml
The [build log](https://swiftpackageindex.com/builds/B3735E2E-96D3-4203-A704-49784C5F167A) on Swift Package Index shows `xcodebuild: error: The workspace named "spi-builder-workspace" does not contain a scheme named "GoogleGenerativeAI". The "-list" option can be used to find the names of the schemes in the workspace.`.
Manually setting the scheme to `generative-ai-swift` (found with `xcodebuild -list`) to see if this resolves the documentation generation failure.
=> Set scheme to `generative-ai-swift` in `.spi.yml`

Tests/GoogleAITests/GenerativeModelTests.swift
Switched a more concise approach for checking the underlying errors in the `GenerativeModelTests`.
=> Switch to shorter `catch let` syntax for checking underlying errors

Sources/GoogleAI/ModelContent.swift
The MIME type was erroneously being set to `"image/jpeg"` in the `ModelContent.png(_:)` convenience method.
Note: PNG images seem (in my limited testing) to be parsed correctly by the backend, even when the MIME type is set to `"image/jpeg"`.
=> Fix MIME type to "image/png" in `ModelContent.png(_:)`

Examples/GenerativeAISample/GenerativeAISample.xcodeproj/project.pbxproj
Fixed a problem in which GenerativeAIUIComponents was missing from the dependency on ChatSample and this sample app could not be built.
|Before|After|
|:-:|:-:|
|![スクリーンショット 2023-12-14 23 55 59](https://github.com/google/generative-ai-swift/assets/13805382/9f28baea-b189-4369-ba68-629b262172d5)|![スクリーンショット 2023-12-14 23 56 46](https://github.com/google/generative-ai-swift/assets/13805382/ee87a254-8a85-48f8-8c9f-a29b793481c3)|
Bug fix
=> Fix missing dependency for ChatSample

.spi.yml
If there's one library the scheme matches the package, otherwise it auto-generates one for the package and generates a scheme for each product
Fix failing spi doc build: https://swiftpackageindex.com/builds/FDA7B1D2-9174-4546-938F-30058E60E466
Choose one: Bug fix
=> Set the scheme for the documentation build

Sources/GoogleAI/GenerativeAISwift.swift
Is this the best way to turn off unsupported targets?
=> Build failure for unsupported platforms

.github/workflows/spm.yml, Package.swift, Sources/GoogleAI/PartsRepresentable.swift, Tests/GoogleAITests/GoogleAITests.swift, scripts/build.sh
- Mac Catalyst apps can import both `UIKit` and `AppKit` but `NSImage` (from `AppKit`) is unavailable in Catalyst
- Re-ordered `#if canImport(UIKit)` before `#elseif canImport(AppKit)` so that the `UIKit` branch is picked in Catalyst builds (`UIImage` is available in Catalyst)
- This builds and tests pass when targeting "`My Mac (Mac Catalyst)`".
=> Add support for Mac Catalyst

Sources/GoogleAI/GenerativeAISwift.swift
Give a warning instead of error for unsupported platforms, since some or most functionality should work on other platforms.
=> Warning instead of error for un-fully supported platforms

Examples/GenerativeAISample/APIKey/APIKey.swift
Added a check for no api key value being present against the `API_KEY` entry in the plist.
I ran into an issue where I was integrating the SDK within my own application. I copied the `APIKey.swift` enum  file to my project & created the `GenerativeAI-Info.plist` file with an `API_KEY` key-value pair but forgot to copy my own api key against it in the plist. The app ran without producing any results for obvious reasons. I figured other users who merely run the Sample app may also run into the same issue wherein they forget to copy their own api key after creating it.
Bug fix
=> Check for empty API_KEY in plist

Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GenerativeModelTests.swift
The [`list models`](https://ai.google.dev/tutorials/rest_quickstart#list_models) REST API returns model names prefixed with `"models/"`, e.g., `"models/gemini-pro"`. This PR allows `GenerativeModel` to be instantiated with or without the `"models/"` on the `name` parameter.
This follows the approach taken in https://github.com/google/generative-ai-go/pull/13.
=> Support model names prefixed with "models/"

Examples/GenerativeAISample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift
Resizes images to fit within 768x768 pixels while maintaining the same aspect ratio. This size was chosen to allow multiple images to be sent within the maximum size limit (4MB at time of writing). See https://googledevai.devsite.corp.google.com/docs/gemini_api_overview#image_requirements for more details.
=> Resize images to 768x768px in GenerativeAIMultimodalSample

Sources/GoogleAI/Errors.swift, Sources/GoogleAI/GenerateContentError.swift, Sources/GoogleAI/GenerativeAIService.swift, Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GenerativeModelTests.swift
Added an `invalidAPIKey` case to `GenerateContentError` to allow developers to catch invalid API key errors at runtime (e.g., when a key is revoked).
Example usage:
```
do {
let content = try await model.generateContent("Why is the sky blue?")
} catch GenerateContentError.invalidAPIKey {
print("The provided API key is invalid.")
}
```
=> Add `invalidAPIKey` case to `GenerateContentError`

Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GenerativeModelTests.swift
- Fixed `generateContentStream` to throw `GenerateContentError.invalidAPIKey` instead of `GenerateContentError.internalError`
- Now matches the `generateContent` behaviour (changed in #91 / #92)
- Added a unit test for this scenario
- Note: Uses the same `unary-failure-api-key.json` sample response as the `generateContent` test since the backend response is the same for both unary and streaming requests
=> Throw `GenerateContentError.invalidAPIKey` in `generateContentStream`

Sources/GoogleAI/Errors.swift, Sources/GoogleAI/GenerateContentError.swift, Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GenerateContentResponses/unary-failure-unsupported-user-location.json, Tests/GoogleAITests/GenerativeModelTests.swift
Added a specific `GenerateContentError` case `unsupportedUserLocation` that is thrown when the API is called from a location not in the list of [available regions](https://ai.google.dev/available_regions#available_regions). Previously, this was thrown as an `internalError`, requiring developers to look at the underlying error to determine the failure reason (#82).
=> Add `unsupportedUserLocation` case to `GenerateContentError`

Examples/GenerativeAISample/ChatSample/Views/ErrorDetailsView.swift
Updated the `ErrorDetailsView` in the Chat Sample to handle the new `GenerateContentError.invalidAPIKey` case and added a Swift Preview for it.
Note: This won't get triggered until #93 is merged.
Preview:
=> Update `ErrorDetailsView` in the Chat Sample to handle `invalidAPIKey`

Examples/GenerativeAISample/ChatSample/Views/ErrorDetailsView.swift
Updated the `ErrorDetailsView` in the Chat Sample to handle the new `GenerateContentError.unsupportedUserLocation` case and added a Swift Preview for it.
Preview:
=> Update Chat Sample to handle `unsupportedUserLocation` case

Sources/GoogleAI/CountTokensRequest.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerativeAIRequest.swift, Sources/GoogleAI/GenerativeAIService.swift, Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GenerativeModelTests.swift
Allows developers to specify configuration options for requests sent to the backend (e.g., the request's timeout).
=> Add `RequestOptions` to `GenerativeModel` constructor

Sources/GoogleAI/CountTokensRequest.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerativeAIRequest.swift, Sources/GoogleAI/GenerativeAIService.swift, Sources/GoogleAI/GenerativeModel.swift
Use `RequestOptions()` as the default value instead of `nil` in the `GenerativeModel` constructor.
=> Make `requestOptions` non-optional in `GenerativeModel`

Package.swift, Sources/GoogleAI/Chat.swift, Sources/GoogleAI/CountTokensRequest.swift, Sources/GoogleAI/GenerateContentError.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerateContentResponse.swift, Sources/GoogleAI/GenerationConfig.swift, Sources/GoogleAI/GenerativeAIRequest.swift, Sources/GoogleAI/GenerativeAIService.swift, Sources/GoogleAI/GenerativeAISwift.swift, Sources/GoogleAI/GenerativeModel.swift, Sources/GoogleAI/Logging.swift, Sources/GoogleAI/ModelContent.swift, Sources/GoogleAI/PartsRepresentable.swift, Sources/GoogleAI/Safety.swift, Tests/GoogleAITests/GoogleAITests.swift, Tests/GoogleAITests/PartsRepresentableTests.swift
- Lowered the minimum supported versions to iOS 11+, macOS 10.13+ and macCatalyst 13+ in the Swift **Package**.
Note: The SDK still requires iOS 15+, macOS 11+ and macCatalyst 15+. This allows apps or other SDKs targeting lower versions to depend on the SDK and using availability guards (e.g., `#available(iOS...`).
=> Lower minimum required OS versions in Swift package

Package.swift
Set `swift-tools-version: 5.7.1` in `Package.swift`. This allows the `generative-ai-swift` package to be used (temporarily/unofficially supported) in Xcode 14.1+.
=> Decrease `swift-tools-version` to `5.7.1`

Sources/GoogleAI/GenerateContentRequest.swift, Tests/GoogleAITests/ChatTests.swift, Tests/GoogleAITests/GenerativeModelTests.swift, Tests/GoogleAITests/MockURLProtocol.swift
Fixed the build in Xcode 14 (locally tested on Xcode 14.2 / Swift 5.7.2 toolchain).
Note: Xcode 14 is unofficially supported (best effort only / temporary).
=> Fix build in Xcode 14 / Swift 5.7.1

Sources/GoogleAI/CountTokensRequest.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerativeAIRequest.swift, Sources/GoogleAI/GenerativeAISwift.swift
Added `apiVersion` to `RequestOptions`, which allows developers to optionally target a specific version of the API (for example, `"v1beta"`); defaults to `"v1"` if not specified.
=> Add `apiVersion` to `RequestOptions`

Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GenerativeModelTests.swift
- Future-proofed the SDK to support additional model name prefixes (e.g., `myPrefix/` in addition to `models/`)
- If no prefix is provided then the default `models/` prefix will be prepended (e.g., `"gemini-pro"` is equivalent to `"models/gemini-pro"`)
=> Add support for additional model name prefixes

Sources/GoogleAI/GenerativeAISwift.swift
Updated `GenerativeAISwift.version` to `0.4.8` in preparation for the next release.
=> Increment SDK version to 0.4.8

Sources/GoogleAI/GenerativeModel.swift
Added a link to https://ai.google.dev/models/gemini in the `GenerativeModel` constructor documentation. This page lists supported model names (e.g., `gemini-pro` and `gemini-pro-vision`).
Screenshot:
=> Add documentation link to the Gemini models list

README.md
Added the following PaLM API deprecation notice to the README:
> The PaLM API is deprecated for use with Google AI services and tools (but _not_ for Vertex AI). Learn more about this deprecation, its timeline, and how to migrate to use Gemini in the [PaLM API deprecation guide](http://ai.google.dev/palm_docs/deprecation).
=> Add deprecation notice for the PaLM API

Examples/GenerativeAICLI/Sources/GenerateContent.swift, Examples/GenerativeAISample/ChatSample/ViewModels/ConversationViewModel.swift, Examples/GenerativeAISample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift, Examples/GenerativeAISample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift, README.md, Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GoogleAITests.swift
Updated model name strings from `gemini-pro` to `gemini-1.0-pro` and from `gemini-pro-vision` to `gemini-1.0-pro-vision-latest`. For a list of model names and details about model versions, generations and variants, see https://ai.google.dev/models/gemini.
=> Update model name strings in README, docs and samples

Sources/GoogleAI/JSONValue.swift, Tests/GoogleAITests/JSONValueTests.swift
Added encoding support for `JSONValue`.
=> Add `Encodable` conformance to `JSONValue`

Sources/GoogleAI/Chat.swift, Sources/GoogleAI/FunctionCalling.swift, Sources/GoogleAI/ModelContent.swift, Tests/GoogleAITests/GenerateContentResponses/unary-success-function-call-empty-arguments.json, Tests/GoogleAITests/GenerateContentResponses/unary-success-function-call-no-arguments.json, Tests/GoogleAITests/GenerateContentResponses/unary-success-function-call-with-arguments.json, Tests/GoogleAITests/GenerativeModelTests.swift
Added a type to represent a [`FunctionCall`](https://ai.google.dev/api/rest/v1beta/Content#functioncall) and implemented `Decodable`.
Note: Merging into the `function-calling` feature branch, not `main`.
=> Add `FunctionCall` decoding

Sources/GoogleAI/ModelContent.swift
Updated the `ModelContent.Part` decoding implementation to throw if `text` or `inlineData` fields are included in the payload but decoding fails. This allows us to see the `DecodingError` thrown instead of it being hidden by `try?`.
This makes it consistent with the discussion in https://github.com/google/generative-ai-swift/pull/114#discussion_r1513373712.
=> Update `ModelContent.Part` enum decoding strategy

Examples/GenerativeAICLI/Sources/GenerateContent.swift, Sources/GoogleAI/FunctionCalling.swift
Updated the constructor for `FunctionDeclaration` to take `parameters: [String: Schema]?, requiredParameters: [String]?` instead of `parameters: Schema?`. This prevents a non-object top-level schema from being provided, e.g., Schema(type: .number, format: "int64", description: "My Int parameter") which isn't supported.
=> Simplify top-level schema declaration in `FunctionDeclaration`

Sources/GoogleAI/GenerativeModel.swift
Removed an unused `tunedModelResourcePrefix` constant from `GenerativeModel`. This was unintentionally left in after the implementation change in [`41a395f` (#98)](https://github.com/google/generative-ai-swift/pull/98/commits/41a395f341bfd040702695a6217c1069c5b05a18).
=> Remove unused `tunedModelResourcePrefix` constant

Examples/GenerativeAICLI/Sources/GenerateContent.swift, Sources/GoogleAI/Chat.swift, Sources/GoogleAI/FunctionCalling.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerativeModel.swift, Sources/GoogleAI/JSONValue.swift, Sources/GoogleAI/ModelContent.swift, Tests/GoogleAITests/GenerateContentResponses/unary-success-function-call-empty-arguments.json, Tests/GoogleAITests/GenerateContentResponses/unary-success-function-call-no-arguments.json, Tests/GoogleAITests/GenerateContentResponses/unary-success-function-call-with-arguments.json, Tests/GoogleAITests/GenerativeModelTests.swift, Tests/GoogleAITests/JSONValueTests.swift
Added manual function calling support.
=> Add function calling support

Sources/GoogleAI/GenerateContentResponse.swift, Tests/GoogleAITests/GenerativeModelTests.swift
Added a computed property that returns the function calls, if any, from the first candidate of a `GenerateContentResponse`.
=> Add `functionCalls` accessor to `GenerateContentResponse`

Examples/GenerativeAICLI/Sources/GenerateContent.swift, Sources/GoogleAI/FunctionCalling.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerativeModel.swift
- Made the `toolConfig` and `functionCallingConfig` parameters optional in constructors / ivars
- Added an `allowedFunctionNames` array for use with `Mode.any`
=> Make `ToolConfig` and `FunctionCallingConfig` optional

Examples/GenerativeAICLI/Sources/GenerateContent.swift, Examples/GenerativeAISample/GenerativeAIUIComponents/Sources/GenerativeAIUIComponents/InputField.swift, Mintfile, Sources/GoogleAI/FunctionCalling.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerativeModel.swift
Implement "forced" (formerly "constrained") function calling
Confirmed the three parameters (ANY, AUTO, NONE) return successfully in the CLI app and NONE disables the function call.
Open Questions:
- Should no parameter be empty instead of "AUTO"?
- If yes, what's the best way to implement?
- What additional testing should be done?
=> Forced function calling

Examples/GenerativeAISample/FunctionCallingSample/Screens/FunctionCallingScreen.swift, Examples/GenerativeAISample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, Examples/GenerativeAISample/GenerativeAISample.xcodeproj/project.pbxproj, Examples/GenerativeAISample/GenerativeAISample/ContentView.swift
Added a new function calling example in the sample app.
=> Add function calling sample

Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GoogleAITests.swift
Added support for providing a [system instruction](https://ai.google.dev/docs/system_instructions) when instantiating a `GenerativeModel`. This can be used to direct the model towards specific behaviour.
Testing Example:
```
let model = GenerativeModel(
name: "gemini-1.5-pro-latest",
apiKey: APIKey.default,
systemInstruction: ModelContent(parts: "Talk like a pirate."),
requestOptions: RequestOptions(apiVersion: "v1beta")
)
let response = try await model.generateContent("Hello")
print(response.text!)
```
> Ahoy there, matey! 🦜  What be bringin' ye to these waters? 🌊
=> Add system instruction support

Sources/GoogleAI/GenerativeAISwift.swift
Updated the SDK version to `0.4.11` in preparation for the next release.
=> Increment SDK version to `0.4.11`

Sources/GoogleAI/GenerateContentResponse.swift, Tests/GoogleAITests/GoogleAITests.swift
- Added tests to verify that the expected symbols in `GenerateContentResponse` are public.
- Added default nil value for `promptFeedback` in the `GenerateContentResponse` constructor to align with Vertex AI.
- This is a port of https://github.com/firebase/firebase-ios-sdk/pull/12791.
=> Add public API tests for `GenerateContentResponse`

README.md
The repo is now in the `google-gemini` GitHub organization instead of `google`. This change broke the Swift Package Index shields.io badges.
=> Fix Swift Package Index badges after org change

Examples/GenerativeAISample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, Sources/GoogleAI/Chat.swift, Sources/GoogleAI/ModelContent.swift
Added support for URI-based file data (in addition to existing support for data as inline bytes). Files may be uploaded using the [`media.upload`](https://ai.google.dev/api/rest/v1beta/media/upload) REST API.
=> Add URI-based file data support

Sources/GoogleAI/GenerativeAIRequest.swift
Updated the default API version from `v1` to `v1beta`. This allows several SDK features, such as function calling and system instructions, and new models, such as `gemini-1.5-pro-latest` to be used without setting `apiVersion` in `RequestOptions` when instantiating a model.
=> Update default API version from `v1` to `v1beta`

Sources/GoogleAI/GenerateContentResponse.swift, Tests/GoogleAITests/GenerativeModelTests.swift
As a follow-up to #135, made `Citation.license` a `String?`. The `license` is now `nil` if not provided by the backend (future-proofing) or if the provided license is an empty string (current response behaviour). This now matches the [`Citation.license`](https://github.com/firebase/firebase-ios-sdk/blob/3783c8a1c3b5058cca47d81b20a903299b1f861f/FirebaseVertexAI/Sources/GenerateContentResponse.swift#L192) public API in the Vertex AI preview.
=> Make `Citation.license` optional

Examples/GenerativeAISample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift
Specifying `RequestOptions(apiVersion: "v1beta")` is no longer necessary in the Function Calling sample since it is the default as of #137.
=> Remove extraneous `apiVersion: "v1beta"` in function calling sample

Sources/GoogleAI/CountTokensRequest.swift, Sources/GoogleAI/FunctionCalling.swift, Sources/GoogleAI/GenerateContentResponse.swift, Sources/GoogleAI/GenerationConfig.swift, Sources/GoogleAI/ModelContent.swift, Sources/GoogleAI/Safety.swift
Removed public `Codable` (`Decodable` and/or `Encodable`) conformance. This is primarily a documentation change, e.g., `Citation` has `init(from: any Decoder) throws` listed as an initializer in the [0.4.1 docs](https://swiftpackageindex.com/google-gemini/generative-ai-swift/0.4.11/documentation/googlegenerativeai/citation#initializers) but it has been removed as of #135 ([docs for main](https://swiftpackageindex.com/google-gemini/generative-ai-swift/main/documentation/googlegenerativeai/citation#default-implementations) -- listed as a Default Implementation only). This change is being proposed to discourage the use of these initializers.
Note: In case the links don't load, Swift Package Index's documentation server appears to be flaky at the moment.
=> Remove public `Codable` (`Decodable` and/or `Encodable`) conformance

.github/workflows/check.yml
Updated to Python 3.10 since Python 3.6 [isn't available](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json) on `arm64`.
- This should fix https://github.com/google-gemini/generative-ai-swift/actions/runs/8819288849/job/24210118892?pr=145#step:3:12
- Aligns with https://github.com/firebase/firebase-ios-sdk/pull/12847
=> Use Python 3.10 in `check` job

README.md
Added a callout to the top of the README that the SDK is recommended for prototyping only.
Note: Replaced the PaLM notice at the top of the file though the more detailed instructions [remain below](https://github.com/google-gemini/generative-ai-swift/blob/main/README.md#developers-who-use-the-palm-sdk-for-swift-deprecated).
=> Add prototyping only recommendation in README

Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GoogleAITests.swift
This change allows developers to write
```
model = GenerativeModel(name: "gemini-1.0-pro", apiKey: APIKey.default, systemInstruction: "Talk like a pirate")
```
instead of 
```
model = GenerativeModel(name: "gemini-1.0-pro", apiKey: APIKey.default, systemInstruction: ModelContent(role: "system", parts: "Talk like a pirate"))
```
=> Allow for a simpler way to set system instructions

Sources/GoogleAI/GenerativeModel.swift
- Updated the `GenerativeModel` constructor taking `systemInstruction: any ThrowingPartsRepresentable...` (from #149) to `systemInstruction: String` since only text input is supported at this time.
- Added example usage to the DocC parameter documentation.
=> Make system instruction accept `String` values only

Sources/GoogleAI/FunctionCalling.swift
Added a default value of `nil` for `requiredParameters` in `FunctionDeclaration`.
=> Add default `nil` value for `requiredParameters` in `FunctionDeclaration`

Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GoogleAITests.swift
Updated the `GenerativeModel` constructor taking `systemInstruction: String` (from #152) to accept a variadic `String...`. The Gemini 1.5 model supports multiple text-only system instructions.
=> Make system instruction accept variadic `String...`

Sources/GoogleAI/GenerativeModel.swift
Moved the `GenerativeModel` convenience constructor accepting a `systemInstruction: ModelContent? = nil` above the one accepting `systemInstruction: String...` in `GenerativeModel.swift`. Xcode's autocomplete seems to order them based on the order they appear in the source file. Previously the first constructor listed appeared to require `systemInstruction`, which might mislead devs into thinking it is required.
Before:
After:
Note: This is not a breaking change, only cosmetic, `systemInstruction: nil` has always been supported since being introduced in the https://github.com/google-gemini/generative-ai-swift/releases/tag/0.4.11.
=> Re-order the `GenerativeModel` convenience constructors in source

Sources/GoogleAI/GenerationConfig.swift, Tests/GoogleAITests/GenerationConfigTests.swift, Tests/GoogleAITests/GoogleAITests.swift
Added a [`responseMIMEType`](https://ai.google.dev/api/rest/v1beta/GenerationConfig) parameter to the `GenerationConfig` constructor to allow configuration of the media type of the generated candidate text (e.g., `"application/json"` to produce JSON text).
=> Add `responseMIMEType` to `GenerationConfig`

Sources/GoogleAI/ModelContent.swift, Tests/GoogleAITests/GoogleAITests.swift, Tests/GoogleAITests/ModelContentTests.swift
- Added JSON encoding tests for `ModelContent.Part.fileData` and an API test. Ported from https://github.com/firebase/firebase-ios-sdk/pull/12886.
- Added a documentation link to the `media.upload` REST API referenced in https://github.com/google-gemini/generative-ai-swift/pull/134.
=> Add `ModelContent` tests for `fileData` parts

Sources/GoogleAI/GenerateContentResponse.swift, Tests/GoogleAITests/GenerateContentResponses/unary-success-function-call-mixed-content.json, Tests/GoogleAITests/GenerateContentResponses/unary-success-function-call-parallel-calls.json, Tests/GoogleAITests/GenerativeModelTests.swift
- Added support for responses that include both `text` and `functionCall` parts (or other content types in the future).
- Note: Multiple `text` parts in a single response is theoretical at this time (may need to revisit the joining approach if the output doesn't match our expectations).
- Also added a test for parallel function calling (multiple `functionCall` parts in one response).
See https://github.com/firebase/firebase-js-sdk/pull/8229 for JS (Vertex AI) equivalent.
=> Make `text` computed property handle mixed-parts responses

Sources/GoogleAI/GenerativeAIRequest.swift, Sources/GoogleAI/GenerativeAIService.swift, Tests/GoogleAITests/GenerativeModelTests.swift
Updated the default request timeout to 300 seconds (5 minutes) instead of using the [platform default](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest#discussion) (currently 60 seconds).
=> Add default `RequestOptions.timeout` of 300 seconds

Examples/GenerativeAICLI/Sources/GenerateContent.swift, Examples/GenerativeAISample/ChatSample/ViewModels/ConversationViewModel.swift, Examples/GenerativeAISample/FunctionCallingSample/ViewModels/FunctionCallingViewModel.swift, Examples/GenerativeAISample/GenerativeAIMultimodalSample/ViewModels/PhotoReasoningViewModel.swift, Examples/GenerativeAISample/GenerativeAITextSample/ViewModels/SummarizeViewModel.swift, README.md
- Updated the samples and documentation to use the `gemini-1.5-flash-latest` model name.
- Removed hardcoded [SafetySetting] and `GenerationConfig` in the CLI tool.
- This lets the server pick the default values.
- CLI tool no longer needs to check for image parts since `gemini-1.5-flash-latest` supports both text-only and multimodal prompts.
=> Update models in samples and README to `gemini-1.5-flash-latest`

Sources/GoogleAI/CountTokensRequest.swift, Sources/GoogleAI/GenerateContentRequest.swift, Sources/GoogleAI/GenerativeModel.swift, Tests/GoogleAITests/GenerateContentRequestTests.swift
- Updated the `countTokens` implementation to populate `generateContentRequest` instead of `contents` in the [request body](https://ai.google.dev/api/rest/v1beta/models/countTokens#request-body).
- This provides a more accurate token count since, e.g., function declarations and system instructions from the request are now counted.
- Updated the `GenerateContentRequest` encoding implementation to serialize the `model` field.
- Currently only needed for `countTokens` but is always serialized (it is ignored by the backend in `generateContent` and `generateContentStream`).
=> Send `GenerateContentRequest` in `CountTokensRequest`

Sources/GoogleAI/GenerativeAIService.swift
Updated logging to print response payloads even when `-GoogleGenerativeAIDebugLogEnabled` is _not_ enabled. This is a port of https://github.com/firebase/firebase-ios-sdk/pull/13009.
<details>
<summary>Example Error Response Log</summary>
If a `responseMIMEType` of `application/json` (JSON mode) is specified for a model that doesn't support it (e.g., `gemini-1.0-pro`):
```
[GoogleGenerativeAI] Response payload: {
"error": {
"code": 400,
"message": "Json mode is not enabled for models/gemini-1.0-pro",
"status": "INVALID_ARGUMENT"
}
}
```
</details>
Updated logging to only print the `NSHTTPURLResponse` if `-GoogleGenerativeAIDebugLogEnabled` is enabled.
<details>
<summary>Example NSHTTPURLResponse Log</summary>
```
[GoogleGenerativeAI] The server responded with an error: <NSHTTPURLResponse: …
```
=> Log server error responses without `-GoogleGenerativeAIDebugLogEnabled`

Package.swift, samples/APIKey.swift, samples/TextGeneration.swift
- Added text generation code snippets for use in documentation.
- Added a `CodeSnippetTests` `testTarget` to the Swift package to ensure that the snippets build.
- These "tests" are skipped (not run, only built) by default, including on CI, but can be run locally by setting the `API_KEY` environment variable in Xcode. They do not contain any assertions but output may be manually inspected.
=> Add code snippets for text generation

samples/FunctionCalling.swift
Add a function calling code snippet for use in documentation. Example based on the JS snippet: https://github.com/google-gemini/generative-ai-js/blob/6dc421876d8998ecea3bb6b40efbacd82b15517b/samples/function_calling.js#L21-L95
=> Add a code snippet for function calling

samples/CountTokens.swift
Added count token code snippets for requests with system instructions and tools.
=> Add count tokens snippets for system instructions and tools

.github/workflows/cli.yml
The start of the CLI workflow [failures](https://github.com/google-gemini/generative-ai-swift/actions/runs/10004031795) seems to coincide with the https://github.com/apple/swift-argument-parser/releases/tag/1.5.0. Bumping the workflow from Xcode 15.0.1 to 15.1 resolves the error.
=> Update Xcode version in CLI workflow

README.md
Markdown [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) (e.g., `[!CAUTION]`) need to be placed on their own line to be rendered correctly.
=> Fix caution callout in README

samples/README.md
I'm making sure all samples in our various repos have a ToC. This matches the Python & REST READMEs, and I can add a GitHub action if you like - just LMK.
* [Python and REST](https://github.com/google-gemini/generative-ai-python/commit/db311dd3f26233206a65b946a17417837ae12905)
* [GitHub action](https://github.com/google-gemini/generative-ai-python/blob/main/.github/workflows/samples.yaml)
=> Add a README for /samples

README.md
Updated references to the PaLM SDK in the `main` branch README since the PaLM API is now decommissioned (as of August 20, 2024). See #204 for more details.
=> Update `main` branch README for PaLM API decommissioning

README.md
Updated the README in the `palm` branch to reflect that the PaLM SDK is now decommissioned (as of August 20, 2024) rather than deprecated.
=> Update `palm` branch README for PaLM API decommissioning

Sources/GoogleAI/GenerativeAISwift.swift
Update version property to 0.5.6 in preparation of next release
Released version 0.5.5 does not match current source version 0.5.4. As a result, SDK requests contain the incorrect version.
`curl -H 'x-goog-api-key: AIz' -H 'Content-Type: application/json' -H 'x-goog-api-client: genai-swift/0.5.4'`
Bug fix
=> Update version to 0.5.6
